# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "Rob's Website"
tagline:          "A GitHub Website"
description:      "Robs's GitHub Website"
url:              http://github.com/Brinker1999

author:
  name:           'Robert B'
  url:            https://github.com/Brinker1999

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Brinker1999/Brinker1999.github.io
